args: 
   environment: none
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.100.1:3306/newwd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: 123456
   jpa:
     database: MYSQL
     hibernate.ddl-auto: update
     show-sql: true 
   profiles:
     active: @profileActive@
server:
   error:
     path: /error 

     
     
     